package commercelayer

const (
	addressType                  = "addresses"
	geocoderType                 = "geocoders"
	merchantType                 = "merchants"
	customerGroupType            = "customer_groups"
	priceListType                = "price_lists"
	webhookType                  = "webhooks"
	externalGatewayType          = "external_gateways"
	externalTaxCalculatorType    = "external_tax_calculators"
	marketType                   = "markets"
	taxCalculatorType            = "tax_calculators"
	inventoryModelType           = "inventory_models"
	shippingMethodType           = "shipping_methods"
	shippingZoneType             = "shipping_zones"
	shippingCategoryType         = "shipping_categories"
	stockLocationType            = "stock_locations"
	inventoryReturnLocationsType = "inventory_return_locations"
	inventoryStockLocationsType  = "inventory_stock_locations"
	deliveryLeadTimesType        = "delivery_lead_times"
	googleGeocodersType          = "google_geocoders"
	bingGeocodersType            = "bing_geocoders"
	paymentMethodType            = "payment_methods"
	paymentGatewayType           = "payment_gateways"
	manualGatewaysType           = "manual_gateways"
	adyenGatewaysType            = "adyen_gateways"
	paypalGatewaysType           = "paypal_gateways"
	klarnaGatewaysType           = "klarna_gateways"
	braintreeGatewaysType        = "braintree_gateways"
	checkoutComGatewaysType      = "checkout_com_gateways"
	stripeGatewaysType           = "stripe_gateways"
	taxjarAccountsType           = "taxjar_accounts"
	skusType                     = "skus"
	manualTaxCalculatorsType     = "manual_tax_calculators"
)
